# Generated by Django 5.1.6 on 2026-03-06 08:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authn", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("requester_name", models.CharField(blank=True, max_length=150)),
                ("requester_email", models.EmailField(blank=True, max_length=254)),
                (
                    "target",
                    models.CharField(
                        help_text="IP, CIDR, domain, or wildcard target", max_length=255
                    ),
                ),
                ("allowed_scanners", models.JSONField(blank=True, default=list)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("smart_contract", "Smart Contract"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("blockchain_tx_hash", models.CharField(blank=True, max_length=128)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consents",
                        to="authn.organization",
                    ),
                ),
            ],
        ),
    ]
