# Generated by Django 5.1.6 on 2026-03-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegionalRiskSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(default="TZ", max_length=3)),
                ("region", models.CharField(blank=True, max_length=128)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("attack_volume", models.PositiveIntegerField(default=0)),
                ("malware_volume", models.PositiveIntegerField(default=0)),
                ("exposure_score", models.FloatField(default=0.0)),
                ("risk_index", models.FloatField(default=0.0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["country_code", "region", "period_end"],
                        name="analytics_r_country_e09fd7_idx",
                    )
                ],
            },
        ),
    ]
