# Generated by Django 5.1.6 on 2026-03-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThreatEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("tzcert", "TZ-CERT"),
                            ("abuseipdb", "AbuseIPDB"),
                            ("otx", "AlienVault OTX"),
                            ("acled", "ACLED"),
                            ("nvd", "NVD"),
                            ("manual", "Manual"),
                        ],
                        max_length=32,
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("occurred_at", models.DateTimeField()),
                ("country_code", models.CharField(default="TZ", max_length=3)),
                ("region", models.CharField(blank=True, max_length=128)),
                ("district", models.CharField(blank=True, max_length=128)),
                ("ward", models.CharField(blank=True, max_length=128)),
                ("indicator", models.CharField(blank=True, max_length=64)),
                ("value", models.CharField(blank=True, max_length=255)),
                ("severity_score", models.FloatField(default=0.0)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source", "occurred_at"],
                        name="osint_threa_source_460e5b_idx",
                    ),
                    models.Index(
                        fields=["country_code", "region"],
                        name="osint_threa_country_82400b_idx",
                    ),
                ],
            },
        ),
    ]
